version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
    groups:
      tezos-packages:
        patterns:
          - "tezos*"
      cranelift-packages:
        patterns:
          - "cranelift*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
