[workspace]
resolver = "3"
members = [
  "src/riscv/lib",
  "durable-storage",
  "data",
  "tools/sandbox",
  "tools/analyse-jit-functions",
  "tools/gen-etherlink-store-accesses",
  "tools/kernel-bench-utils",
  "test-utils",
]
exclude = ["kernels"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
unwrap_used = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "allow"

[workspace.dependencies]
anyhow = "1.0"
arbitrary-int = "2.1.1"
bincode = "2.0"
blake3 = "1.8.3"
bytes = "1.11.1"
capstone = "0.14"
cfg-if = "1.0.4"
comfy-table = "7.2.2"
const_format = "0.2"
cranelift = "0.120.2"
cranelift-jit = "0.120.1"
cranelift-module = "0.120.1"
cranelift-native = "0.120.2"
criterion = "0.8.2"
ed25519-dalek = "2.2.0"
elf = "0.8.0"
enum-tag = "0.3.0"
gdbstub = "0.7.9"
gdbstub_arch = "0.3.2"
goldenfile = "1.10.0"
ieee-apsqrt = "0.1.1"
itertools = "0.14.0"
lazy_static = "1.5.0"
libsecp256k1 = "0.7.2"
log = "0.4.29"
meansd = "2.1.0"
memmap2 = "0.9.9"
num_enum = "0.7.5"
numfmt = "1.2.0"
object = "0.38"
paste = "1.0.14"
perfect-derive = "0.1.5"
proptest = "1.10.0"
quanta = "0.12.6"
rand = "0.10.0"
range-collections = "0.4.6"
rustc-demangle = "0.1"
rocksdb = "0.24.0"
rustc_apfloat = "0.2.3"
serde_json = "1.0.149"
sha2 = "0.10.9"
sha3 = "0.10.8"
tempfile = "3.24.0"
thiserror = "2.0.18"
trait-set = "0.3.0"
try-blocks = "0.1.4"
tuples = "1.20.1"
unty = "0.0.4"
vm-fdt = "0.3.0"
zerocopy = "0.8.39"
zerocopy-derive = "0.8.27"
rangemap = "1.7.1"

[workspace.dependencies.tezos-smart-rollup-constants]
git = "https://gitlab.com/tezos/tezos.git"

[workspace.dependencies.tezos-smart-rollup-encoding]
git = "https://gitlab.com/tezos/tezos.git"

[workspace.dependencies.tezos-smart-rollup-utils]
git = "https://gitlab.com/tezos/tezos.git"

[workspace.dependencies.tezos-smart-rollup]
git = "https://gitlab.com/tezos/tezos.git"
features = ["utils"]

[workspace.dependencies.tezos_crypto_rs]
git = "https://gitlab.com/tezos/tezos.git"
default-features = false

[workspace.dependencies.strum]
version = "0.27.2"
features = ["derive"]

[workspace.dependencies.clap]
version = "4.5.59"
features = ["derive"]

[workspace.dependencies.datadog-api-client]
version = "0.26.0"
default-features = false
features = ["rustls-tls"]

[workspace.dependencies.derive_more]
version = "2.1.1"
features = ["debug", "display", "from", "into", "error"]

[workspace.dependencies.serde]
version = "1.0.228"
features = ["derive"]

[workspace.dependencies.hex]
version = "0.4.3"
features = ["serde"]


[workspace.dependencies.tokio]
version = "1"
features = ["full"]

[workspace.dependencies.octez-riscv]
path = "src/riscv/lib"

[workspace.dependencies.octez-riscv-durable-storage]
path = "durable-storage"
default-features = false

[workspace.dependencies.octez-riscv-data]
path = "data"

[workspace.dependencies.octez-riscv-test-utils]
path = "test-utils"

# The dependency alias is used to make it obvious that it should not be used directly. Using it
# directly may have a surprising impact on performance when logging and tracing are disabled.
[workspace.dependencies.__tracing_do_not_use_directly]
package = "tracing"
version = "0.1.41"

[workspace.dependencies.tracing-subscriber]
version = "0.3.22"
features = ["json", "env-filter"]
