[package]
name = "octez-riscv-durable-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bincode.workspace = true
bytes.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
goldenfile.workspace = true
log.workspace = true
hex.workspace = true
perfect-derive.workspace = true
octez-riscv-data.workspace = true
rand.workspace = true
rocksdb.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
trait-set.workspace = true

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
octez-riscv-test-utils.workspace = true
serde.workspace = true
serde_json.workspace = true

[[bench]]
name = "avl_tree"
harness = false

[[bench]]
name = "database"
harness = false
