[package]
name = "octez-riscv-durable-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["rocksdb"]
unstable-test-utils = [
  "dep:clap",
  "dep:proptest",
  "dep:serde",
  "dep:serde_with",
  "dep:anyhow",
  "dep:serde_json",
  "dep:rkyv",
  "octez-riscv-data/unstable-test-utils",
]

[dependencies]
bincode.workspace = true
bytes.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
goldenfile.workspace = true
libc.workspace = true
log.workspace = true
hex.workspace = true
perfect-derive.workspace = true
octez-riscv-data.workspace = true
once_cell.workspace = true
rand.workspace = true
tempfile.workspace = true
tezos-smart-rollup-constants.workspace = true
thiserror.workspace = true
tokio.workspace = true
trait-set.workspace = true

[dependencies.rocksdb]
workspace = true
optional = true

[dependencies.anyhow]
workspace = true
optional = true

[dependencies.clap]
workspace = true
optional = true

[dependencies.serde_json]
workspace = true
optional = true

[dependencies.proptest]
workspace = true
optional = true

[dependencies.rkyv]
workspace = true
optional = true

[dependencies.serde]
workspace = true
optional = true

[dependencies.serde_with]
workspace = true
optional = true

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
octez-riscv-durable-storage = { path = ".", features = ["unstable-test-utils"] }
octez-riscv-test-utils.workspace = true
serde.workspace = true
serde_json.workspace = true

[[bin]]
name = "long_test"
path = "src/bin/long_test.rs"
required-features = ["rocksdb", "unstable-test-utils"]

[[bin]]
name = "gc_space"
path = "src/bin/gc_space.rs"
required-features = ["rocksdb", "unstable-test-utils"]

[[bench]]
name = "avl_tree"
harness = false

[[bench]]
name = "avl_storage"
harness = false

[[bench]]
name = "database"
harness = false
required-features = ["rocksdb"]

[[bench]]
name = "database_checkout"
harness = false
required-features = ["rocksdb"]

[[bench]]
name = "database_lifecycle"
harness = false
required-features = ["rocksdb"]
