# SPDX-FileCopyrightText: 2026 TriliTech <contact@trili.tech>
# SPDX-License-Identifier: MIT

all: check

check:
	@cargo clippy --all-targets --no-default-features -- --deny warnings

.PHONY: all check
