# SPDX-FileCopyrightText: 2026 TriliTech <contact@trili.tech>
# SPDX-License-Identifier: MIT

all: check

check: 
	@cargo check --all-targets --no-default-features
	@cargo check --all-targets

.PHONY: all check
