// SPDX-FileCopyrightText: 2025 TriliTech <contact@trili.tech>
//
// SPDX-License-Identifier: MIT

use std::cell::RefCell;
use std::collections::VecDeque;
use std::io::Read;
use std::marker::PhantomData;
use std::rc::Rc;

use bincode::Decode;

use super::LeafTag;
use super::Tag;
use super::deserialiser::Deserialiser;
use super::deserialiser::DeserialiserNode;
use super::deserialiser::Partial;
use super::deserialiser::ProofLayoutResult;
use super::deserialiser::Suspended;
use crate::state_backend::ProofLayoutError;
use crate::state_backend::ProofParseError;
use crate::state_backend::TagError;
use crate::state_backend::proof_backend::proof::InvalidTagError;
use crate::state_backend::proof_backend::proof::NotEnoughBytesError;
use crate::state_backend::proof_backend::proof::deserialiser;
use crate::state_backend::proof_backend::proof::deserialiser::ProofParseResult;
use crate::state_backend::proof_backend::proof::deserialiser::RunDeserialiser;
use crate::storage::Hash;

/// Wrapper type over the raw byte data to parse tags.
pub struct TagIter<'i> {
    buffered_tags: VecDeque<Result<Tag, InvalidTagError>>,
    raw_data_iter: std::io::Cursor<&'i [u8]>,
}

impl Iterator for TagIter<'_> {
    type Item = Result<Tag, InvalidTagError>;
    fn next(&mut self) -> Option<Self::Item> {
        if self.buffered_tags.is_empty() {
            // We have to consume the next byte
            let mut next_byte = [0u8];
            let byte = match self.raw_data_iter.read_exact(&mut next_byte) {
                Ok(()) => next_byte[0],
                Err(_eof) => return None,
            };
            let tags = Tag::ordered_tags_from_u8(byte);
            self.buffered_tags.extend(tags);
        }
        self.buffered_tags.pop_front()
    }
}
impl<'i> TagIter<'i> {
    /// Create a [`TagIter`] from a `&[u8]`
    pub fn new(raw_data: &'i [u8]) -> Self {
        TagIter {
            buffered_tags: VecDeque::new(),
            raw_data_iter: std::io::Cursor::new(raw_data),
        }
    }
    /// Convert the remaining unparsed bytes as a [`StreamInput`] for further deserialising.
    pub fn remaining_to_stream_input(&self) -> StreamInput<'_> {
        StreamInput {
            // This clone only copies the reference and the position, not the whole byte array.
            cursor: self.raw_data_iter.clone(),
        }
    }
}

/// Input used for the suspended computation generated by [`StreamDeserialiser`]
pub struct StreamInput<'cd> {
    cursor: std::io::Cursor<&'cd [u8]>,
}

impl StreamInput<'_> {
    /// Interpret the next bytes as `T` using [`Decode`].
    fn deserialise<T: Decode<()>>(&mut self) -> ProofParseResult<T> {
        Ok(crate::storage::binary::deserialise_from(&mut self.cursor)?)
    }
}

/// Deserialiser for [`Deserialiser`] based on a stream of bytes.
#[derive(Clone)]
pub enum StreamDeserialiser<'t> {
    Absent,
    Present { tags: Rc<RefCell<TagIter<'t>>> },
}

impl<'t> Deserialiser for StreamDeserialiser<'t> {
    type Suspended<R> = StreamParserComb<'t, R>;

    type DeserialiserNode<R> = StreamBranchComb<'t, R>;

    fn into_leaf_raw<const LEN: usize>(
        self,
    ) -> ProofLayoutResult<Self::Suspended<Partial<Box<[u8; LEN]>>>> {
        let tag = match self.next_tag() {
            None => {
                return Ok(StreamParserComb::new(|_| Ok(Partial::Absent)));
            }
            Some(Err(err)) => return Err(err.into()),
            Some(Ok(tag)) => tag,
        };
        Ok(StreamParserComb::new(match tag {
            Tag::Node => return Err(ProofLayoutError::UnexpectedNode),
            Tag::Leaf(leaf_type) => move |input: &mut StreamInput| match leaf_type {
                LeafTag::Blind => Ok(Partial::Blinded(input.deserialise::<Hash>()?)),
                LeafTag::Read => {
                    let mut data = Box::new([0_u8; LEN]);
                    match input.cursor.read_exact(data.as_mut()) {
                        Ok(()) => Ok(Partial::Present(data)),
                        Err(_eof) => Err(NotEnoughBytesError.into()),
                    }
                }
            },
        }))
    }

    fn into_leaf<T: Decode<()>>(self) -> ProofLayoutResult<Self::Suspended<Partial<(T, Vec<u8>)>>> {
        let tag = match self.next_tag() {
            None => {
                return Ok(StreamParserComb::new(|_| Ok(Partial::Absent)));
            }
            Some(Err(err)) => return Err(err.into()),
            Some(Ok(tag)) => tag,
        };
        Ok(StreamParserComb::new(match tag {
            Tag::Node => return Err(ProofLayoutError::UnexpectedNode),
            Tag::Leaf(leaf_type) => move |input: &mut StreamInput| match leaf_type {
                LeafTag::Blind => Ok(Partial::Blinded(input.deserialise::<Hash>()?)),
                LeafTag::Read => Ok({
                    let initial_position = input.cursor.position() as usize;
                    let data = input.deserialise::<T>()?;
                    let end_position = input.cursor.position() as usize;
                    let raw_bytes = input.cursor.get_ref()[initial_position..end_position].to_vec();
                    Partial::Present((data, raw_bytes))
                }),
            },
        }))
    }

    fn into_node(self) -> ProofLayoutResult<Self::DeserialiserNode<Partial<()>>> {
        let tags = match self {
            StreamDeserialiser::Absent => {
                return Ok(StreamBranchComb {
                    f: Box::new(|_| Ok(Partial::Absent)),
                    node_state: None,
                });
            }
            StreamDeserialiser::Present { tags } => tags,
        };

        let tag = tags
            .borrow_mut()
            .next()
            .ok_or(TagError::NotEnoughBytes(NotEnoughBytesError))?
            .map_err(TagError::InvalidTag)?;

        match tag {
            Tag::Leaf(LeafTag::Read) => Err(ProofLayoutError::UnexpectedLeaf),
            Tag::Leaf(LeafTag::Blind) => Ok(StreamBranchComb {
                f: Box::new(move |input: &mut StreamInput| {
                    Ok(Partial::Blinded(input.deserialise()?))
                }),
                node_state: None,
            }),
            Tag::Node => Ok(StreamBranchComb {
                f: Box::new(|_| Ok(Partial::Present(()))),
                node_state: Some(tags),
            }),
        }
    }
}

impl<'t> StreamDeserialiser<'t> {
    /// Create a new [`StreamDeserialiser::Present`] with the given tags.
    pub fn new_present(tags: Rc<RefCell<TagIter<'t>>>) -> Self {
        StreamDeserialiser::Present { tags }
    }

    /// Obtain next tag based on the current state of the deserialiser.
    ///
    /// Return [`None`] if the parent node is absent / blinded - making it nonsensical
    /// to obtain any tags.  
    fn next_tag(&self) -> Option<Result<Tag, TagError>> {
        // Panic: Never actually panics because the mutable borrow is first used only while deserialising,
        // Only after all tags are parsed the mutable borrow is used when running the Suspended computation.
        // Since the deserialiser & suspended traits never expose a way for running the suspended computation
        // this guarantees the sequential use of mutable borrows.
        match self {
            StreamDeserialiser::Absent => None,
            StreamDeserialiser::Present { tags } => Some(
                tags.borrow_mut()
                    .next()
                    .ok_or(TagError::NotEnoughBytes(NotEnoughBytesError))
                    .and_then(|tag| tag.map_err(TagError::InvalidTag)),
            ),
        }
    }
}

/// Parser combinator for [`StreamDeserialiser`] deserialiser.
pub struct StreamParserComb<'t, R> {
    #[expect(
        clippy::type_complexity,
        reason = "FnOnce is a trait and trait aliases are not stable yet"
    )]
    f: Box<dyn FnOnce(&mut StreamInput) -> ProofParseResult<R> + 'static>,
    _pd: PhantomData<fn(StreamInput<'t>)>,
}

impl<'t, R> Suspended for StreamParserComb<'t, R> {
    type Output = R;

    type Parent = StreamDeserialiser<'t>;

    fn map<T>(
        self,
        map_f: impl FnOnce(Self::Output) -> T + 'static,
    ) -> <Self::Parent as Deserialiser>::Suspended<T>
    where
        Self::Output: 'static,
    {
        StreamParserComb::new(move |input| {
            let r = (self.f)(input)?;
            Ok(map_f(r))
        })
    }
}

impl<R> StreamParserComb<'_, R> {
    /// Create a new [`StreamParserComb`] with the given function.
    pub fn new(f: impl FnOnce(&mut StreamInput) -> ProofParseResult<R> + 'static) -> Self {
        StreamParserComb {
            f: Box::new(f),
            _pd: PhantomData,
        }
    }
}

/// Branch combinator for [`StreamDeserialiser`] deserialiser.
pub struct StreamBranchComb<'t, R> {
    #[expect(
        clippy::type_complexity,
        reason = "FnOnce is a trait and trait aliases are not stable yet"
    )]
    f: Box<dyn FnOnce(&mut StreamInput) -> ProofParseResult<R> + 'static>,
    /// The none case represents that the father node was blind or absent.
    node_state: Option<Rc<RefCell<TagIter<'t>>>>,
}

impl<'t, R> DeserialiserNode<R> for StreamBranchComb<'t, R> {
    type Parent = StreamDeserialiser<'t>;

    fn next_branch<T>(
        self,
        branch_deserialiser: impl FnOnce(
            Self::Parent,
        ) -> ProofLayoutResult<
            <Self::Parent as Deserialiser>::Suspended<T>,
        >,
    ) -> ProofLayoutResult<<Self::Parent as Deserialiser>::DeserialiserNode<(R, T)>>
    where
        T: 'static,
        R: 'static,
    {
        let child_proof = match &self.node_state {
            Some(tags) => StreamDeserialiser::new_present(tags.clone()),
            None => StreamDeserialiser::Absent,
        };
        let next_branch_fn = branch_deserialiser(child_proof)?;

        Ok(StreamBranchComb {
            f: Box::new(move |input| {
                // We still have to apply the parser combinator, it may compute the Hash for the blinded case for example
                // or any other intermediate function the user made on the computation using `map`
                let r = (self.f)(input)?;

                // The same logic applies for the child branch, maybe the user maps the Absent result to something else.
                let br_res = (next_branch_fn.f)(input)?;

                Ok((r, br_res))
            }),
            node_state: self.node_state,
        })
    }

    fn map<T>(
        self,
        f: impl FnOnce(R) -> T + 'static,
    ) -> <Self::Parent as Deserialiser>::DeserialiserNode<T>
    where
        T: 'static,
        R: 'static,
    {
        StreamBranchComb {
            f: Box::new(move |input| Ok(f((self.f)(input)?))),
            node_state: self.node_state,
        }
    }

    fn done(self) -> ProofLayoutResult<<Self::Parent as Deserialiser>::Suspended<R>> {
        Ok(StreamParserComb {
            f: self.f,
            _pd: PhantomData,
        })
    }
}

impl<R> StreamParserComb<'_, R> {
    /// Deserialise the input and return the result if all bytes have been consumed.  
    pub fn into_result(self, input: &mut StreamInput) -> ProofParseResult<R> {
        let result = (self.f)(input);

        // A correct deserialisation makes sure all bytes are consumed.
        // Otherwise, if tags dictate more a bigger part of the proof has been blinded then
        // the extra data at the end which wasn't actually blinded remains unparsed / ignored.

        // XXX: has_data_left() can be used, but it is a nightly feature
        // tracking issue: <https://github.com/rust-lang/rust/issues/86423>
        let mut next_byte = [0_u8];
        match input.cursor.read_exact(&mut next_byte) {
            Ok(()) => Err(ProofParseError::RemainingBytes),
            Err(_eof) => Ok(result?),
        }
    }
}

impl<'t> RunDeserialiser for StreamDeserialiser<'t> {
    type Data = &'t [u8];

    fn run<R>(
        input_data: Self::Data,
        deser_fn: impl FnOnce(Self) -> ProofLayoutResult<<Self as Deserialiser>::Suspended<R>>,
    ) -> deserialiser::Result<R> {
        let tags = Rc::new(RefCell::new(TagIter::new(input_data)));
        let comp_fn = deser_fn(StreamDeserialiser::new_present(tags.clone()))?;

        // SAFETY: The `Deserialiser` trait provided to the `FromProof` implementation of T
        // can not execute the suspended computation, it can only compose them due to encapsulation
        comp_fn
            .into_result(&mut tags.borrow_mut().remaining_to_stream_input())
            .map_err(deserialiser::Error::ParseProof)
    }
}
