// SPDX-FileCopyrightText: 2025 TriliTech <contact@trili.tech>
//
// SPDX-License-Identifier: MIT

use std::io::Read;

use bincode::Decode;

use super::LeafTag;
use super::Tag;
use super::deserialiser::Deserialiser;
use super::deserialiser::DeserialiserNode;
use super::deserialiser::Partial;
use super::deserialiser::Result;
use super::deserialiser::Suspended;
use crate::state_backend::AllocatedOf;
use crate::state_backend::OwnedProofPart;
use crate::state_backend::ProofError;
use crate::state_backend::ProofLayout;
use crate::state_backend::proof_backend::proof::NotEnoughBytesError;
use crate::state_backend::proof_backend::proof::deserialiser;
use crate::state_backend::verify_backend::Verifier;
use crate::storage::Hash;

/// Input used for the suspended computation generated by [`StreamDeserialiser`]
pub struct StreamInput<'cd> {
    data: &'cd [u8],
}

impl<'t> StreamInput<'t> {
    /// Create a value of [`StreamInput`] that will be used to deserialise a proof.
    pub fn new(data: &'t [u8]) -> Self {
        StreamInput { data }
    }

    /// Interpret the next bytes as `T` using [`Decode`].
    fn deserialise<T: Decode<()>>(&mut self) -> Result<T> {
        Ok(crate::storage::binary::deserialise_from(&mut self.data)?)
    }

    /// Like [`Self::deserialise`] but also returns the raw bytes that were used to deserialise `T`.
    fn capture_deserialise<T: Decode<()>>(&mut self) -> Result<(T, &'t [u8])> {
        let start_pos = self.data;
        let data = self.deserialise::<T>()?;
        let end_pos = self.data;

        let data_len = start_pos.len() - end_pos.len();
        let raw_bytes = &start_pos[..data_len];

        Ok((data, raw_bytes))
    }

    /// Have we reached the end of the stream yet?
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

/// Current deserialisation context with regards to presence of the parent node
enum Presence {
    /// Absent node context
    ///
    /// This is because the parent node is either absent or blinded. In both cases, the potential
    /// child nodes are not contained in the proof, hence we consider them absent for the purpose
    /// of deserialisation.
    Absent,

    /// Present node context
    ///
    /// The parent is contained in the proof, hence we make no assumptions on the existence of
    /// child nodes.
    Present,
}

/// Deserialiser for [`Deserialiser`] based on a stream of bytes.
pub struct StreamDeserialiser<'t> {
    /// Context layers with regard to presence
    ///
    /// The last element describes the current node context. The first element describes the root
    /// context.
    ///
    /// Contextual presence information is needed to allow moving the tag source through the
    /// different combinators without losing track of whether the parent node is currently absent
    /// or present.
    context: Vec<Presence>,

    /// Source of tags
    ///
    /// The tag source is present unconditionally because it may be passed to a parent layer. That
    /// is because we require the ability to recover the tag source from a combinator for an
    /// absent node.
    input: StreamInput<'t>,
}

impl<'t> StreamDeserialiser<'t> {
    /// Create a new deserialiser for a present context with the given tags.
    pub fn new_present(input: StreamInput<'t>) -> Self {
        StreamDeserialiser {
            context: vec![Presence::Present],
            input,
        }
    }

    /// Create a new deserialiser for an absent context with the given tags.
    pub fn new_absent() -> Self {
        StreamDeserialiser {
            context: vec![Presence::Absent],
            input: StreamInput::new(&[]),
        }
    }

    /// Obtain the next tag from the tag source.
    fn next_tag(&mut self) -> Result<Tag> {
        self.input.deserialise::<Tag>()
    }

    /// Check if the current context is for an absent or blinded node.
    fn is_absent(&self) -> bool {
        matches!(self.context.last(), Some(Presence::Absent) | None)
    }

    /// Enter a context for an absent node.
    fn enter_absent(mut self) -> Self {
        self.context.push(Presence::Absent);
        self
    }

    /// Enter a context for a present node.
    fn enter_present(mut self) -> Self {
        self.context.push(Presence::Present);
        self
    }

    /// Exit the current context.
    fn exit_context(mut self) -> Self {
        self.context.pop();
        self
    }
}

impl<'t> Deserialiser for StreamDeserialiser<'t> {
    type Suspended<R> = StreamParserComb<'t, R>;

    type DeserialiserNode<R> = StreamBranchComb<'t, R>;

    fn into_leaf_raw<const LEN: usize>(
        mut self,
    ) -> Result<Self::Suspended<Partial<Box<[u8; LEN]>>>> {
        if self.is_absent() {
            return Ok(StreamParserComb::new(self, Partial::Absent));
        }

        let tag = self.next_tag()?;

        let result = match tag {
            Tag::Node => return Err(ProofError::UnexpectedNode),
            Tag::Leaf(leaf_type) => match leaf_type {
                LeafTag::Blind => Partial::Blinded(self.input.deserialise::<Hash>()?),
                LeafTag::Read => {
                    let mut data = Box::new([0_u8; LEN]);

                    if self.input.data.read_exact(data.as_mut()).is_err() {
                        return Err(ProofError::NotEnoughBytes(NotEnoughBytesError));
                    };

                    Partial::Present(data)
                }
            },
        };

        Ok(StreamParserComb::new(self, result))
    }

    fn into_leaf<T: Decode<()>>(mut self) -> Result<Self::Suspended<Partial<(T, Vec<u8>)>>> {
        if self.is_absent() {
            return Ok(StreamParserComb::new(self, Partial::Absent));
        }

        let tag = self.next_tag()?;

        let result = match tag {
            Tag::Node => return Err(ProofError::UnexpectedNode),
            Tag::Leaf(leaf_type) => match leaf_type {
                LeafTag::Blind => Partial::Blinded(self.input.deserialise::<Hash>()?),
                LeafTag::Read => {
                    let (data, raw_bytes) = self.input.capture_deserialise::<T>()?;
                    Partial::Present((data, raw_bytes.to_vec()))
                }
            },
        };

        Ok(StreamParserComb::new(self, result))
    }

    fn into_node(mut self) -> Result<Self::DeserialiserNode<Partial<()>>> {
        if self.is_absent() {
            return Ok(StreamBranchComb {
                result: Partial::Absent,
                deser: self.enter_absent(),
            });
        }

        let tag = self.next_tag()?;

        match tag {
            Tag::Leaf(LeafTag::Read) => Err(ProofError::UnexpectedLeaf),
            Tag::Leaf(LeafTag::Blind) => Ok(StreamBranchComb {
                result: Partial::Blinded(self.input.deserialise::<Hash>()?),
                deser: self.enter_absent(),
            }),
            Tag::Node => Ok(StreamBranchComb {
                result: Partial::Present(()),
                deser: self.enter_present(),
            }),
        }
    }
}

/// Parser combinator for [`StreamDeserialiser`] deserialiser.
pub struct StreamParserComb<'t, R> {
    /// Parser result
    result: R,

    /// Parent deserialiser
    deser: StreamDeserialiser<'t>,
}

impl<'t, R> Suspended for StreamParserComb<'t, R> {
    type Output = R;

    type Parent = StreamDeserialiser<'t>;

    fn map<T>(
        self,
        map_f: impl FnOnce(Self::Output) -> T,
    ) -> <Self::Parent as Deserialiser>::Suspended<T> {
        StreamParserComb {
            result: map_f(self.result),
            deser: self.deser,
        }
    }
}

impl<'t, R> StreamParserComb<'t, R> {
    /// Create a new [`StreamParserComb`] with the given function.
    fn new(deser: StreamDeserialiser<'t>, result: R) -> Self {
        StreamParserComb { result, deser }
    }
}

/// Branch combinator for [`StreamDeserialiser`] deserialiser.
pub struct StreamBranchComb<'t, R> {
    /// Branch result
    result: R,

    /// Parent deserialiser
    deser: StreamDeserialiser<'t>,
}

impl<'t, R> DeserialiserNode<R> for StreamBranchComb<'t, R> {
    type Parent = StreamDeserialiser<'t>;

    fn next_branch<T>(
        self,
        branch_deserialiser: impl FnOnce(
            Self::Parent,
        )
            -> Result<<Self::Parent as Deserialiser>::Suspended<T>>,
    ) -> Result<<Self::Parent as Deserialiser>::DeserialiserNode<(R, T)>> {
        let next_branch = branch_deserialiser(self.deser)?;

        Ok(StreamBranchComb {
            result: (self.result, next_branch.result),

            // We need to recover the deserialiser from the child branch.
            deser: next_branch.deser,
        })
    }

    fn map<T>(self, f: impl FnOnce(R) -> T) -> <Self::Parent as Deserialiser>::DeserialiserNode<T> {
        StreamBranchComb {
            result: f(self.result),
            deser: self.deser,
        }
    }

    fn done(self) -> Result<<Self::Parent as Deserialiser>::Suspended<R>> {
        Ok(StreamParserComb {
            result: self.result,
            deser: self.deser.exit_context(),
        })
    }
}

impl<R> StreamParserComb<'_, R> {
    /// Deserialise the input and return the result if all bytes have been consumed.
    pub fn into_result(self) -> Result<R> {
        if !self.deser.input.is_empty() {
            // Ending with left over bytes indicates that we have not parsed the proof correctly.
            // It could be that we have interpreted data as tags, or vice versa.
            return Err(ProofError::RemainingBytes);
        }

        Ok(self.result)
    }
}

/// Deserialise raw bytes into a [`Verifier`] backend and the partial state hash helper [`OwnedProofPart`].
///
/// Convenience function to bundle deserialisation and execution of the suspended function for the owned deserialisation.
pub fn deserialise<L: ProofLayout>(
    proof_tree_raw_bytes: &[u8],
) -> deserialiser::Result<(AllocatedOf<L, Verifier>, OwnedProofPart)> {
    let input = StreamInput::new(proof_tree_raw_bytes);
    let comp_fn = L::into_verifier_alloc(StreamDeserialiser::new_present(input))?;

    // SAFETY: The `Deserialiser` trait provided to the `FromProof` implementation of T
    // can not execute the suspended computation, it can only compose them due to encapsulation
    comp_fn.into_result()
}
