[env]
CC_wasm32_unknown_unknown = "clang"
CC_riscv64gc_unknown_hermit = "clang"
CC_riscv64gc_unknown_linux_musl = "riscv64-unknown-linux-musl-cc"

[build]
rustdocflags = ["--deny", "warnings"]

[profile.profiling]
inherits = "release"
debug = true

[profile.test]
opt-level = 1

# Required in order to build OCaml bindings with ocaml-rs on MacOS
[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.riscv64gc-unknown-linux-musl]
linker = "riscv64-unknown-linux-musl-gcc"
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "default-linker-libraries=y",
]
