// SPDX-FileCopyrightText: 2026 TriliTech <contact@trili.tech>
//
// SPDX-License-Identifier: MIT

//! Binary Merkle tree proof format

use std::io::Read;
use std::marker::PhantomData;

use bincode::Decode;
use bincode::error::DecodeError;

use crate::codec::Bincode;
use crate::codec::LeafCodec;
use crate::codec::LeafDecode;
use crate::hash::Hash;
use crate::merkle_proof::Deserialiser;
use crate::merkle_proof::DeserialiserNode;
use crate::merkle_proof::FromProof;
use crate::merkle_proof::Partial;
use crate::merkle_proof::ProofError;
use crate::merkle_proof::Suspended;
use crate::merkle_proof::proof_tree::OwnedProofTree;
use crate::merkle_proof::tag::LeafTag;
use crate::merkle_proof::tag::Tag;
use crate::serialisation::deserialise_from;

/// Input used for the suspended computation generated by [`StreamDeserialiser`]
pub struct StreamInput<'cd> {
    data: &'cd [u8],
}

impl<'t> StreamInput<'t> {
    /// Create a value of [`StreamInput`] that will be used to deserialise a proof.
    pub fn new(data: &'t [u8]) -> Self {
        StreamInput { data }
    }

    /// Interpret the next bytes as `T` using [`Decode`].
    fn deserialise<T: Decode<()>>(&mut self) -> Result<T, ProofError> {
        Ok(deserialise_from(&mut self.data)?)
    }

    /// Like [`Self::deserialise`] but decodes a leaf value with codec `C` and also returns the raw
    /// bytes that were consumed.
    fn capture_deserialise<C: LeafCodec, T: LeafDecode<C>>(
        &mut self,
    ) -> Result<(T, &'t [u8]), ProofError> {
        let start_pos = self.data;
        let (data, consumed) = T::leaf_decode_stream(self.data)?;
        self.data = &self.data[consumed..];

        let raw_bytes = &start_pos[..consumed];

        Ok((data, raw_bytes))
    }

    /// Have we reached the end of the stream yet?
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

/// Deserialiser for [`Deserialiser`] based on a stream of bytes.
///
/// Parameterised by the leaf [`LeafCodec`]; defaults to [`Bincode`]. Only leaf decoding depends on
/// the codec — the tag/blind-hash structure is always bincode-encoded.
pub struct StreamDeserialiser<'t, C = Bincode> {
    /// Context layers with regard to presence
    ///
    /// The last element describes the current node context. The first element describes the root
    /// context.
    ///
    /// Contextual presence information is needed to allow moving the tag source through the
    /// different combinators without losing track of whether the parent node is currently absent
    /// or present.
    context: Vec<Partial<()>>,

    /// Source of tags
    ///
    /// The tag source is present unconditionally because it may be passed to a parent layer. That
    /// is because we require the ability to recover the tag source from a combinator for an
    /// absent node.
    input: StreamInput<'t>,

    _codec: PhantomData<C>,
}

impl<'t, C: LeafCodec> StreamDeserialiser<'t, C> {
    /// Create a new deserialiser for a present context with the given tags.
    pub fn new_present(input: StreamInput<'t>) -> Self {
        Self::new(input, Partial::Present(()))
    }

    /// Create a new deserialiser for an absent context with the given tags.
    pub fn new_absent() -> Self {
        Self::new(StreamInput::new(&[]), Partial::Absent)
    }

    /// Create a new deserialiser for a given context with the given tags.
    fn new(input: StreamInput<'t>, context: Partial<()>) -> Self {
        StreamDeserialiser {
            context: vec![context],
            input,
            _codec: PhantomData,
        }
    }

    /// Obtain the next tag from the tag source.
    fn next_tag(&mut self) -> Result<Tag, ProofError> {
        self.input.deserialise::<Tag>()
    }

    /// Check if the current context is for an absent or blinded node.
    fn is_absent_or_blinded(&self) -> bool {
        matches!(
            self.context.last(),
            Some(Partial::Absent) | Some(Partial::Blinded(_)) | None
        )
    }

    /// Enter a context for a node with the given presence.
    fn enter_context(mut self, presence: Partial<()>) -> Self {
        self.context.push(presence);
        self
    }

    /// Exit the current context.
    fn exit_context(mut self) -> Self {
        self.context.pop();
        self
    }

    /// Get the presence of the current context.
    fn presence(&self) -> Partial<()> {
        self.context.last().cloned().unwrap_or(Partial::Absent)
    }
}

impl<'t, C: LeafCodec> Deserialiser for StreamDeserialiser<'t, C> {
    type Error = ProofError;

    type Codec = C;

    type Suspended<R> = StreamParserComb<'t, C, R>;

    type DeserialiserNode = StreamBranchComb<'t, C>;

    fn into_leaf_raw<const LEN: usize>(
        mut self,
    ) -> Result<Self::Suspended<Partial<Box<[u8; LEN]>>>, ProofError> {
        if self.is_absent_or_blinded() {
            return Ok(StreamParserComb {
                result: Partial::Absent,
                proof: OwnedProofTree::leaf_from_partial(Partial::Absent, std::convert::identity),
                deser: self,
            });
        }

        let tag = self.next_tag()?;

        let (result, proof) = match tag {
            Tag::Node => return Err(ProofError::UnexpectedNode),
            Tag::Leaf(leaf_type) => match leaf_type {
                LeafTag::Blind => {
                    let hash = self.input.deserialise::<Hash>()?;
                    let result = Partial::Blinded(hash);
                    let proof = Partial::Blinded(hash);
                    (result, proof)
                }
                LeafTag::Read => {
                    let mut data = Box::new([0_u8; LEN]);

                    if self.input.data.read_exact(data.as_mut()).is_err() {
                        return Err(ProofError::Deserialise(DecodeError::UnexpectedEnd {
                            additional: data.len(),
                        }));
                    };

                    let proof = Partial::Present(data.as_ref().to_vec());
                    let result = Partial::Present(data);

                    (result, proof)
                }
            },
        };

        let proof = OwnedProofTree::leaf_from_partial(proof, std::convert::identity);

        Ok(StreamParserComb {
            result,
            proof,
            deser: self,
        })
    }

    fn into_leaf<T: LeafDecode<C>>(mut self) -> Result<Self::Suspended<Partial<T>>, ProofError> {
        if self.is_absent_or_blinded() {
            let this = StreamParserComb {
                result: Partial::Absent,
                proof: OwnedProofTree::leaf_from_partial(Partial::Absent, std::convert::identity),
                deser: self,
            };
            return Ok(this);
        }

        let tag = self.next_tag()?;

        let (result, proof) = match tag {
            Tag::Node => return Err(ProofError::UnexpectedNode),
            Tag::Leaf(leaf_type) => match leaf_type {
                LeafTag::Blind => {
                    let hash = self.input.deserialise::<Hash>()?;
                    let result = Partial::Blinded(hash);
                    let proof = Partial::Blinded(hash);
                    (result, proof)
                }
                LeafTag::Read => {
                    let (data, raw_bytes) = self.input.capture_deserialise::<C, T>()?;
                    let result = Partial::Present(data);
                    let proof = Partial::Present(raw_bytes.to_vec());
                    (result, proof)
                }
            },
        };

        let proof = OwnedProofTree::leaf_from_partial(proof, std::convert::identity);

        Ok(StreamParserComb {
            result,
            proof,
            deser: self,
        })
    }

    fn into_node(mut self) -> Result<Self::DeserialiserNode, ProofError> {
        if self.is_absent_or_blinded() {
            let this = StreamBranchComb {
                proof_children: Vec::new(),
                deser: self.enter_context(Partial::Absent),
            };
            return Ok(this);
        }

        let tag = self.next_tag()?;

        match tag {
            Tag::Leaf(LeafTag::Read) => Err(ProofError::UnexpectedLeaf),
            Tag::Leaf(LeafTag::Blind) => {
                let hash = self.input.deserialise::<Hash>()?;
                let result = Partial::Blinded(hash);
                let this = StreamBranchComb {
                    proof_children: Vec::new(),
                    deser: self.enter_context(result),
                };
                Ok(this)
            }
            Tag::Node => {
                let result = Partial::Present(());
                let this = StreamBranchComb {
                    proof_children: Vec::new(),
                    deser: self.enter_context(result),
                };
                Ok(this)
            }
        }
    }
}

/// Parser combinator for [`StreamDeserialiser`] deserialiser.
pub struct StreamParserComb<'t, C, R> {
    /// Parser result
    result: R,

    /// Proof that represents the parsed parts
    proof: OwnedProofTree,

    /// Parent deserialiser
    deser: StreamDeserialiser<'t, C>,
}

impl<C, R> StreamParserComb<'_, C, R> {
    /// Deserialise the input and return the result if all bytes have been consumed.
    pub fn into_result(self) -> Result<(R, OwnedProofTree), ProofError> {
        if !self.deser.input.is_empty() {
            // Ending with left over bytes indicates that we have not parsed the proof correctly.
            // It could be that we have interpreted data as tags, or vice versa.
            return Err(ProofError::RemainingBytes);
        }

        Ok((self.result, self.proof))
    }
}

impl<'t, C: LeafCodec, R> Suspended for StreamParserComb<'t, C, R> {
    type Output = R;

    type Parent = StreamDeserialiser<'t, C>;

    fn map<T>(
        self,
        map_f: impl FnOnce(Self::Output) -> T,
    ) -> <Self::Parent as Deserialiser>::Suspended<T> {
        StreamParserComb {
            result: map_f(self.result),
            deser: self.deser,
            proof: self.proof,
        }
    }
}

/// Branch combinator for [`StreamDeserialiser`] deserialiser.
pub struct StreamBranchComb<'t, C> {
    /// Children of the node within the Merkle proof
    proof_children: Vec<OwnedProofTree>,

    /// Parent deserialiser
    deser: StreamDeserialiser<'t, C>,
}

impl<'t, C: LeafCodec> DeserialiserNode for StreamBranchComb<'t, C> {
    type Parent = StreamDeserialiser<'t, C>;

    fn presence(&self) -> Partial<()> {
        self.deser.presence()
    }

    fn next_branch_with<T>(
        self,
        branch_deserialiser: impl FnOnce(
            Self::Parent,
        ) -> Result<
            <Self::Parent as Deserialiser>::Suspended<T>,
            ProofError,
        >,
    ) -> Result<(Self, T), ProofError> {
        let Self {
            deser,
            mut proof_children,
        } = self;

        let StreamParserComb {
            result,
            proof,
            deser,
        } = branch_deserialiser(deser)?;
        proof_children.push(proof);

        let this = StreamBranchComb {
            deser,
            proof_children,
        };

        Ok((this, result))
    }

    fn done<T>(self, value: T) -> Result<<Self::Parent as Deserialiser>::Suspended<T>, ProofError> {
        Ok(StreamParserComb {
            result: value,
            proof: OwnedProofTree::node_from_children(self.deser.presence(), self.proof_children),
            deser: self.deser.exit_context(),
        })
    }
}

/// Deserialise raw bytes as `T` and the partial state hash helper [`OwnedProofTree`].
///
/// Convenience function to bundle deserialisation and execution of the suspended function for the]
/// binary proof format deserialisation.
pub fn deserialise<C: LeafCodec, T: FromProof<C>>(
    proof_tree_raw_bytes: &[u8],
) -> Result<(T, OwnedProofTree), ProofError> {
    let input = StreamInput::new(proof_tree_raw_bytes);
    let context = StreamDeserialiser::<C>::new_present(input);

    let result = T::from_proof(context)?;

    // SAFETY: The `Deserialiser` trait provided to the `FromProof` implementation of T
    // can not execute the suspended computation, it can only compose them due to encapsulation
    result.into_result()
}
