[package]
name = "analyse-jit-functions"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
capstone.workspace = true
clap.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
