[package]
name = "riscv-tx-kernel"
version = "0.0.0"
edition = "2021"

[dependencies.tezos-smart-rollup]
git = "https://gitlab.com/tezos/tezos.git"
version = "0.2.2"
default-features = false
features = [
  "debug_alloc",
  "proto-alpha",
  "panic-hook",
  "data-encoding",
  "alloc",
  "experimental-host-in-memory-store",
]

[dependencies]
alloy-eip2930 = "=0.2.1"
alloy-eip7702 = "=0.6.1"
alloy-eips = "=1.0.38"
alloy-primitives = "=1.4.1"
revm = { version = "=33.1.0", default-features = false, features = ["std"] }
rlp = { version = "0.5", default-features = false }
ruint = "=1.17.0"

[dependencies.tezos-smart-rollup-constants]
git = "https://gitlab.com/tezos/tezos.git"

