[package]
name = "octez-riscv-data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
unstable-test-utils = ["dep:proptest", "dep:serde"]

[dependencies]
bincode.workspace = true
blake3.workspace = true
hex.workspace = true
thiserror.workspace = true
perfect-derive.workspace = true
trait-set.workspace = true
memmap2.workspace = true
range-collections.workspace = true
rkyv.workspace = true
bytes.workspace = true
unty.workspace = true

[dependencies.serde]
workspace = true
optional = true

[dependencies.derive_more]
workspace = true
features = ["from_str"]

[dependencies.proptest]
workspace = true
optional = true

[dev-dependencies]
proptest.workspace = true
rand.workspace = true
humansize.workspace = true
goldenfile.workspace = true
clap.workspace = true

[[bench]]
name = "proof"
harness = false
required-features = ["unstable-test-utils"]
