# SPDX-FileCopyrightText: 2026 TriliTech <contact@trili.tech>
# SPDX-License-Identifier: MIT

all: check

check:
	@pnpx mint broken-links
	@pnpx mint validate

dev:
	@pnpx mint dev

.PHONY: all check dev
